### ISSUE TITLE
Unable to cast to Chromecast

### ISSUE THREAD

**Issue by sachib** [dhleong/babbling#18]
Hi,
I'm trying to cast a video to my Chromecast. I've tried 'Hulu', 'Amazon-Prime' and 'Youtube'. I see the app being launched on Chromecast but no content playback. 

Error: no answer from Chromecast device
    at Timeout._onTimeout (/usr/lib/node_modules/babbling/node_modules/nodecastor/lib/channel.js:237:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by dhleong** [comment]
Hmm. I've seen that error rarely, but not consistently enough to know the cause (it's in the low-level chromecast communication library this builds on). 

How are you invoking babbling? Have you ensured your auth is up-to-date? Youtube support should actually work without auth as long as you don't give it a private playlist, or try to resume viewing a playlist.

If your auth is definitely in good order, then communication timeouts like this typically are caused by router configuration....

**Comment by sachib** [comment]
I have babbling installed through npm globally. This is error I see for YouTube:
$ babbling cast "https://www.youtube.com/watch?v=Z8mXRwX1s50" --device "Chromecast-Sachi"
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
babbling cast <url>

Cast a video by URL

Positionals:
  url  The URL to play                                       [string] [required]

Options:
  --version     Show version number                                    [boolean]
  --help        Show help                                              [boolean]
  --config, -c  Config file path
             [string] [default: "/home/sachi/.config/babbling/auto-config.json"]
  --device, -d  The name of the Chromecast device to cast to [string] [required]

TypeError: Cannot read property 'statusCode' of undefined
    at YoutubeApp.<anonymous> (/usr/lib/node_modules/babbling/dist/apps/youtube/index.js:369:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/babbling/dist/apps/youtube/index.js:7:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

For Hulu, this is what I saw:
sachi@USSALNX4176:~/quickset/quickset-suite/ipcontrol/C$ babbling auto-auth
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
This process will attempt to extract authentication for as many Apps as
possible from Chrome. You should close Chrome now for this to complete
successfully.

On macOS you will be prompted to enter a password so we can decrypt
cookies for some apps.

Press enter to continue
Extracted auth:
{ HboGoApp: undefined,
  HuluApp:
   { cookies:
      'guid=; _ga=; _gid=; _tq_id.TV-81453654-1.edd5=; _gcl_au=; _scid=; _sctr=; _hulu_pgid=; _hulu_uid=����C�; _....' },
  YoutubeApp:
   { cookies:
      'VISITOR_INFO1_LIVE=; SID=; __Secure-3PSID=L\u0015.....' } }
Wrote config to: /home/sachi/.config/babbling/auto-config.json
$ babbling cast "https://www.hulu.com/watch/671f8878-bdba-40bd-ae6d-f85c55cecbb4" --device "Chromecast-Sachi"
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
babbling cast <url>

Cast a video by URL

Positionals:
  url  The URL to play                                       [string] [required]

Options:
  --version     Show version number                                    [boolean]
  --help        Show help                                              [boolean]
  --config, -c  Config file path
             [string] [default: "/home/sachi/.config/babbling/auto-config.json"]
  --device, -d  The name of the Chromecast device to cast to [string] [required]

{ RequestError: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
    at new RequestError (/usr/lib/node_modules/babbling/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/babbling/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/babbling/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/babbling/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.start (/usr/lib/node_modules/babbling/node_modules/request/request.js:753:10)
    at Request.end (/usr/lib/node_modules/babbling/node_modules/request/request.js:1505:10)
    at end (/usr/lib/node_modules/babbling/node_modules/request/request.js:564:14)
    at Immediate.<anonymous> (/usr/lib/node_modules/babbling/node_modules/request/request.js:578:7)
    at runCallback (timers.js:705:18)
  name: 'RequestError',
  message:
   'TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]',
  cause:
   TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
       at ClientRequest.setHeader (_http_outgoing.js:473:3)
       at new ClientRequest (_http_client.js:203:14)
       at Object.request (https.js:289:10)
       at Request.start (/usr/lib/node_modules/babbling/node_modules/request/request.js:751:32)
       at Request.end (/usr/lib/node_modules/babbling/node_modules/request/request.js:1505:10)
       at end (/usr/lib/node_modules/babbling/node_modules/request/request.js:564:14)
       at Immediate.<anonymous> (/usr/lib/node_modules/babbling/node_modules/request/request.js:578:7)
       at runCallback (timers.js:705:18)
       at tryOnImmediate (timers.js:676:5)
       at processImmediate (timers.js:658:5),
  error:
   TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
       at ClientRequest.setHeader (_http_outgoing.js:473:3)
       at new ClientRequest (_http_client.js:203:14)
       at Object.request (https.js:289:10)
       at Request.start (/usr/lib/node_modules/babbling/node_modules/request/request.js:751:32)
       at Request.end (/usr/lib/node_modules/babbling/node_modules/request/request.js:1505:10)
       at end (/usr/lib/node_modules/babbling/node_modules/request/request.js:564:14)
       at Immediate.<anonymous> (/usr/lib/node_modules/babbling/node_modules/request/request.js:578:7)
       at runCallback (timers.js:705:18)
       at tryOnImmediate (timers.js:676:5)
       at processImmediate (timers.js:658:5),
  options:
   { headers:
      { Cookie:
         'guid=; _ga=; _gid=; _tq_id.TV-81453654-1.edd5=; _gcl_au=; _scid=; _sctr=; _hulu_pgid=; _hulu_uid=<D',
        Origin: 'https://www.hulu.com',
        Referer: 'https://www.hulu.com/',
        'User-Agent':
         'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36' },
     json: true,
     qs: { entity_id: '671f8878-bdba-40bd-ae6d-f85c55cecbb4' },
     url:
      'https://discover.hulu.com/content/v4/entity/deeplink?schema=2&referral_host=www.hulu.com',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }

I am able to successfully launch YouTube and playback content using pychromecast from the same system to the same Chromecast.

**Comment by sachib** [comment]
Closed by mistake.

**Comment by dhleong** [comment]
Very odd. Definitely never seen that warning about "Apple Bonjour compatibility," which seems a likely cause of connectivity issues. I'm also not sure why you're getting weird binary data in your cookies, which is causing the Hulu errors.

You can fix the cookie errors this way:

1. Open chrome, go to hulu.com and login
2. Open the chrome dev tools (probably ctrl+shift+i) and navigate to the "Network" tab
3. Hit the "XHR" filter, and refresh the page
4. Right-click on one of the lines that looks like "state?eab_ids=..." and go to copy > copy request headers
5. Paste this into an empty text document
6. Find the line that stats with `Cookie:`; copy everything after that colon
7. Paste it into `$HOME/.config/babbling/auto-config.json` under `HuluApp > cookies`. It should look like:

```
{
  "HuluApp": {
    "cookies": "YOUR_COOKIES_HERE"
  }
}
```

where `YOUR_COOKIES_HERE` is what you copied in step 6.

**Comment by sachib** [comment]
Thank you! Grabbing the cookie manually got hulu working. I still have issues with HboGO and Amazon Prime.

sachi@USSALNX4176:~$ sudo babbling cast "https://play.hbogo.com/feature/urn:hbo:feature:GXdcWngMJg5uAuwEAACwu?reentered=true&userProfileType=liteUserProfile" --device "Chromecast-Sachi"
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
babbling cast <url>

Cast a video by URL

Positionals:
  url  The URL to play                                       [string] [required]

Options:
  --version     Show version number                                    [boolean]
  --help        Show help                                              [boolean]
  --config, -c  Config file path
             [string] [default: "/home/sachi/.config/babbling/auto-config.json"]
  --device, -d  The name of the Chromecast device to cast to [string] [required]

Error: Error
    at HboGoApp.<anonymous> (/usr/lib/node_modules/babbling/dist/apps/hbogo/index.js:94:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/babbling/dist/apps/hbogo/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

It says 'It reports error code 11 (problem communicating with server) on the chromecast.

For Amazon Prime Video, it gets stuck in app loading screen and returns this error:
sachi@USSALNX4176:~$ babbling cast "https://www.amazon.com/gp/video/detail/B07MX1QQX7/ref=atv_hm_hom_1_c_FXZSG7_4_5" --device "Chromecast-Sachi"
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
babbling cast <url>

Cast a video by URL

Positionals:
  url  The URL to play                                       [string] [required]

Options:
  --version     Show version number                                    [boolean]
  --help        Show help                                              [boolean]
  --config, -c  Config file path
             [string] [default: "/home/sachi/.config/babbling/auto-config.json"]
  --device, -d  The name of the Chromecast device to cast to [string] [required]

Error: no answer from Chromecast device
    at Timeout._onTimeout (/usr/lib/node_modules/babbling/node_modules/nodecastor/lib/channel.js:237:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

I have no issues casting either app to the same Chromecast through Chrome browser.

**Comment by dhleong** [comment]
Great! 

If that got Hulu working, you ought to be able to fix HboGo in a similar way to Hulu. Instead of looking at the `Cookie` header, however, you want the `Authorization` header. Put everything after the word `Bearer` into the `token` key.

For Amazon, have you done the extra auth step? See: https://github.com/dhleong/babbling#amazon-video

**Comment by sachib** [comment]
I got HBO Go working! I did have the right token all along. I had to change the format of the URL from "https://play.hbogo.com/feature/urn:hbo:episode:GV7xwpQbVEMMbwgEAAAHt?reentered=true&userProfileType=liteUserProfile" to "https://play.hbogo.com/feature/urn:hbo:episode:GV7xwpQbVEMMbwgEAAAHt"
I have authenticated Amazon Prime with 'babbling auth:prime' command. I do see a PrimeApp entry with cookies in the config.json. Perhaps it's another issue with the URL?
I tried various combinations of "https://www.amazon.com/gp/video/detail/B00C15QNSA/ref=atv_hm_hom_1_c_Tco32S_3_2" with no luck.
Do you have an example URL?

**Comment by dhleong** [comment]
Good to know! I should probably make the url handling a bit more flexible.

Try getting rid of the /ref and everything after.

**Comment by sachib** [comment]
I have already tried that without any luck. Here are the combinations I've tried:
"https://www.amazon.com/gp/video/detail/B00C15QNSA/ref=atv_hm_hom_1_c_Tco32S_3_2"
"https://www.amazon.com/gp/video/detail/B00C15QNSA"
"https://www.amazon.com/gp/video/detail/B00C15QNSA/"

**Comment by dhleong** [comment]
Hmm it's possible Amazon's changed something; I haven't been using it
recently, but some videos that used to work are showing "video unavailable."

**Comment by sachib** [comment]
Ok. I'll close this issue and open one specific to Amazon Prime.
