### ISSUE TITLE
Casting to Amazon Prime returns Video Unavailable Error

### ISSUE THREAD

**Issue by sachib** [dhleong/babbling#19]
babbling cast "https://www.amazon.com/gp/video/detail/B07MX1QQX7" --device "Chromecast-Sachi"
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
babbling cast

Cast a video by URL

Positionals:
url The URL to play [string] [required]

Options:
--version Show version number [boolean]
--help Show help [boolean]
--config, -c Config file path
[string] [default: "/home/sachi/.config/babbling/auto-config.json"]
--device, -d The name of the Chromecast device to cast to [string] [required]

Error: no answer from Chromecast device
at Timeout._onTimeout (/usr/lib/node_modules/babbling/node_modules/nodecastor/lib/channel.js:237:12)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)

**Comment by dhleong** [comment]
Hey @sachib I just sat down to look into this and discovered that everything's working just fine again. Has anything changed for you?

**Comment by dhleong** [comment]
This may have been fixed by 58593c965a80ae9d43a83db91a5a37b130c50916, to be released in version `1.23.5`. Please open a new issue if this still occurs!
